[test]
coverage = true
coverageReporter = ["text", "lcov"]
coverageThreshold = { line = 0.9, function = 0.9, statement = 0.9 }
coverageSkipTestFiles = true
coverageDir = "./coverage"
coveragePathIgnorePatterns = [
  "**/dist/**",
  "**/node_modules/**",
  "**/example/**",
  "**/src/server/index.ts",
  "**/src/cli.ts",
  "**/src/client/main.ts",
  "**/src/client/components/**",
  "**/src/client/renderers/markdown.ts"
]
